APP_NAME = "Advanced Calculator"
APP_VERSION = "3.0"

DEFAULT_UI_FONT_CANDIDATES = [
    "Segoe UI",
    "Helvetica",
    "Arial",
    "Noto Sans",
    "DejaVu Sans",
]

DEFAULT_MONO_FONT_CANDIDATES = [
    "Menlo",
    "Consolas",
    "Monaco",
    "Courier New",
    "Liberation Mono",
]


THEMES = {

    "Classic": {
        "bg": "#f5f5f5",
        "fg": "#111111",
        "panel_bg": "#ffffff",
        "panel_fg": "#111111",
        "display_bg": "#ffffff",
        "display_fg": "#111111",
        "border": "#d0d0d0",
        "accent": "#2b7cff",
        "button_bg": "#fafafa",
        "button_fg": "#111111",
        "button_num_bg": "#fafafa",
        "button_num_fg": "#111111",
        "button_op_bg": "#ffcc80",
        "button_op_fg": "#111111",
        "button_fn_bg": "#eaeaea",
        "button_fn_fg": "#111111",
        "button_mem_bg": "#e3f2fd",
        "button_mem_fg": "#0b3d91",
        "button_eq_bg": "#81c784",
        "button_eq_fg": "#0b2a12",
        "button_hover_bg": "#cce7ff",
        "button_active_bg": "#dcdcdc",
        "status_bg": "#eeeeee",
        "status_fg": "#111111",
        "menu_bg": "#f5f5f5",
        "menu_fg": "#111111",
        "menu_active_bg": "#dbe9ff",
        "menu_active_fg": "#111111",
    },

    "Modern Dark": {
        "bg": "#1e1e1e",
        "fg": "#f5f5f5",
        "panel_bg": "#2b2b2b",
        "panel_fg": "#f5f5f5",
        "display_bg": "#121212",
        "display_fg": "#f5f5f5",
        "border": "#3a3a3a",
        "accent": "#00e5ff",
        "button_bg": "#303030",
        "button_fg": "#f5f5f5",
        "button_num_bg": "#303030",
        "button_num_fg": "#f5f5f5",
        "button_op_bg": "#ffb74d",
        "button_op_fg": "#1a1a1a",
        "button_fn_bg": "#424242",
        "button_fn_fg": "#f5f5f5",
        "button_mem_bg": "#263238",
        "button_mem_fg": "#b2ebf2",
        "button_eq_bg": "#00c853",
        "button_eq_fg": "#0b1a10",
        "button_hover_bg": "#3f3f3f",
        "button_active_bg": "#4a4a4a",
        "status_bg": "#252525",
        "status_fg": "#cfcfcf",
        "menu_bg": "#2b2b2b",
        "menu_fg": "#f5f5f5",
        "menu_active_bg": "#3a3a3a",
        "menu_active_fg": "#00e5ff",
    },

    "Ocean Blue": {
        "bg": "#d9ecff",
        "fg": "#003366",
        "panel_bg": "#eef6ff",
        "panel_fg": "#003366",
        "display_bg": "#ffffff",
        "display_fg": "#003366",
        "border": "#b4d3ff",
        "accent": "#0b6bff",
        "button_bg": "#ffffff",
        "button_fg": "#003366",
        "button_num_bg": "#ffffff",
        "button_num_fg": "#003366",
        "button_op_bg": "#90caf9",
        "button_op_fg": "#003366",
        "button_fn_bg": "#e3f2fd",
        "button_fn_fg": "#003366",
        "button_mem_bg": "#b3e5fc",
        "button_mem_fg": "#003366",
        "button_eq_bg": "#1e88e5",
        "button_eq_fg": "#ffffff",
        "button_hover_bg": "#d6ebff",
        "button_active_bg": "#c6defa",
        "status_bg": "#eef6ff",
        "status_fg": "#003366",
        "menu_bg": "#eef6ff",
        "menu_fg": "#003366",
        "menu_active_bg": "#d6ebff",
        "menu_active_fg": "#003366",
    },

    "Green Matrix": {
        "bg": "#001100",
        "fg": "#00ff66",
        "panel_bg": "#001b00",
        "panel_fg": "#00ff66",
        "display_bg": "#000a00",
        "display_fg": "#00ff66",
        "border": "#003300",
        "accent": "#00ff66",
        "button_bg": "#002200",
        "button_fg": "#00ff66",
        "button_num_bg": "#002200",
        "button_num_fg": "#00ff66",
        "button_op_bg": "#004d1a",
        "button_op_fg": "#a8ffbf",
        "button_fn_bg": "#003300",
        "button_fn_fg": "#a8ffbf",
        "button_mem_bg": "#003d1a",
        "button_mem_fg": "#a8ffbf",
        "button_eq_bg": "#00c853",
        "button_eq_fg": "#001100",
        "button_hover_bg": "#003d1a",
        "button_active_bg": "#004d1a",
        "status_bg": "#001b00",
        "status_fg": "#00ff66",
        "menu_bg": "#001b00",
        "menu_fg": "#00ff66",
        "menu_active_bg": "#003300",
        "menu_active_fg": "#a8ffbf",
    },

    "Purple Neon": {
        "bg": "#2d0036",
        "fg": "#ff66ff",
        "panel_bg": "#3a0046",
        "panel_fg": "#ffccff",
        "display_bg": "#1b001f",
        "display_fg": "#ff66ff",
        "border": "#5a0070",
        "accent": "#ff66ff",
        "button_bg": "#3a0046",
        "button_fg": "#ffccff",
        "button_num_bg": "#3a0046",
        "button_num_fg": "#ffccff",
        "button_op_bg": "#6a00a3",
        "button_op_fg": "#ffffff",
        "button_fn_bg": "#4a005c",
        "button_fn_fg": "#ffccff",
        "button_mem_bg": "#4a005c",
        "button_mem_fg": "#ffd6ff",
        "button_eq_bg": "#ff66ff",
        "button_eq_fg": "#1b001f",
        "button_hover_bg": "#520066",
        "button_active_bg": "#5a0070",
        "status_bg": "#3a0046",
        "status_fg": "#ffccff",
        "menu_bg": "#3a0046",
        "menu_fg": "#ffccff",
        "menu_active_bg": "#520066",
        "menu_active_fg": "#ff66ff",
    },

    "Soft Pink": {
        "bg": "#ffe6f2",
        "fg": "#cc0066",
        "panel_bg": "#fff3f8",
        "panel_fg": "#7a0040",
        "display_bg": "#ffffff",
        "display_fg": "#7a0040",
        "border": "#ffc1dc",
        "accent": "#ff4da6",
        "button_bg": "#ffffff",
        "button_fg": "#7a0040",
        "button_num_bg": "#ffffff",
        "button_num_fg": "#7a0040",
        "button_op_bg": "#ffb3d9",
        "button_op_fg": "#7a0040",
        "button_fn_bg": "#ffe0f0",
        "button_fn_fg": "#7a0040",
        "button_mem_bg": "#ffd6ea",
        "button_mem_fg": "#7a0040",
        "button_eq_bg": "#ff4da6",
        "button_eq_fg": "#ffffff",
        "button_hover_bg": "#ffe0f0",
        "button_active_bg": "#ffd1e8",
        "status_bg": "#fff3f8",
        "status_fg": "#7a0040",
        "menu_bg": "#fff3f8",
        "menu_fg": "#7a0040",
        "menu_active_bg": "#ffe0f0",
        "menu_active_fg": "#cc0066",
    },

    "Minimal White": {
        "bg": "#ffffff",
        "fg": "#222222",
        "panel_bg": "#ffffff",
        "panel_fg": "#222222",
        "display_bg": "#ffffff",
        "display_fg": "#111111",
        "border": "#e6e6e6",
        "accent": "#111111",
        "button_bg": "#ffffff",
        "button_fg": "#111111",
        "button_num_bg": "#ffffff",
        "button_num_fg": "#111111",
        "button_op_bg": "#f2f2f2",
        "button_op_fg": "#111111",
        "button_fn_bg": "#f7f7f7",
        "button_fn_fg": "#111111",
        "button_mem_bg": "#f7f7f7",
        "button_mem_fg": "#111111",
        "button_eq_bg": "#111111",
        "button_eq_fg": "#ffffff",
        "button_hover_bg": "#f2f2f2",
        "button_active_bg": "#eaeaea",
        "status_bg": "#f7f7f7",
        "status_fg": "#222222",
        "menu_bg": "#ffffff",
        "menu_fg": "#222222",
        "menu_active_bg": "#f2f2f2",
        "menu_active_fg": "#111111",
    },

    "Cyberpunk": {
        "bg": "#0f0f0f",
        "fg": "#00ffff",
        "panel_bg": "#131313",
        "panel_fg": "#f5f5f5",
        "display_bg": "#070707",
        "display_fg": "#00ffff",
        "border": "#2b2b2b",
        "accent": "#ff00ff",
        "button_bg": "#1a1a1a",
        "button_fg": "#f5f5f5",
        "button_num_bg": "#1a1a1a",
        "button_num_fg": "#f5f5f5",
        "button_op_bg": "#ff00ff",
        "button_op_fg": "#0f0f0f",
        "button_fn_bg": "#222222",
        "button_fn_fg": "#00ffff",
        "button_mem_bg": "#222222",
        "button_mem_fg": "#ffeb3b",
        "button_eq_bg": "#00ffff",
        "button_eq_fg": "#0f0f0f",
        "button_hover_bg": "#242424",
        "button_active_bg": "#2b2b2b",
        "status_bg": "#131313",
        "status_fg": "#bdbdbd",
        "menu_bg": "#131313",
        "menu_fg": "#f5f5f5",
        "menu_active_bg": "#242424",
        "menu_active_fg": "#00ffff",
    }
}
